### ISSUE TITLE
Animation of the transition freezing and hanging

### ISSUE THREAD

**Issue by ivanmood0** [smmr0/gnome-reorder-workspaces#6]
The extension works great, but there is one but ...
After enabling this extension, the animation of the transition (input/output) in the view mode is very freezing and hanging.

Ubuntu 20.04
Gnome 3.36

**Comment by tudorsmt** [comment]
+1 for me. This is also happening, to a lesser extent (choppy animation), on my (quite powerful) machine.

**Comment by abrac** [comment]
I'm also facing this in Ubuntu 20.10, Gnome 3.38. 

I made a recording of it so that others can understand what we're talking about:


https://user-images.githubusercontent.com/55248999/117995433-9b056400-b341-11eb-8ac4-81be0278c89a.mp4

**Comment by G-dH** [comment]
This problem is apparently caused by binding keyboard shortcuts every time you enter overview and removing them on leave.
@ivanmood0 if I remember correctly, you helped me to fix my extension [Custom Hot Corners - Extended](https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/) and I've added ws reordering actions to it as well as custom keyboard shortcuts.

**Comment by rstanuwijaya** [comment]
+1 up, also experiencing this issue when enabling the extension

**Comment by G-dH** [comment]
@rstanuwijaya You can try the [OFP extension](https://github.com/G-dH/vertical-workspaces) which also allows workspace reordering in the overview but without this issue. Oh, only if you use GS 41,42..

**Comment by eyrent** [comment]
Same issue here. Fedora 37 Gnome 43

**Comment by smmr0** [comment]
As @G-dH said, the reason for the choppy animation is that this extension adds its keybindings when the overview is opened and removes its keybindings when the overview is closed; this is so that the keybindings behave normally outside of the overview. For example, if you're using an application that has its own keybinding for `Alt`+`Up`, and if this extension's keybindings are aren't removed when the overview is closed, then the application's keybinding won't work. As far as I can tell, there is no way around this besides the current implementation.

However, for many users it may be acceptable for the keybindings not to work outside of the overview if it results in a smoother animation; and other users may prefer that the keybindings reorder workspaces even if the overview isn't open (see #5). #18 adds an extension setting that allows users to control this behavior; please try it out once it's released!

Thank you to everyone who reported this and contributed to this conversation. :heart: And if anyone knows of any other workarounds to avoid choppy animation with the default behavior, please let me know or submit a pull request.
